version: '3.4'

services:
  server:
    build: .
    container_name: shop_zadatak
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: shop
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local